### ISSUE TITLE
pod用不了啊

### ISSUE THREAD

**Issue by AndSync** [1691665955/MZRefresh#2]
[!] CocoaPods could not find compatible versions for pod "MZRefresh":
  In Podfile:
    MZRefresh (~> 0.0.4)

None of your spec sources contain a spec satisfying the dependency: `MZRefresh (~> 0.0.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by 1691665955** [comment]
使用pod repo update更新下本地仓库
