### ISSUE TITLE
只有上拉加载，导致不能手动触发上拉加载逻辑

### ISSUE THREAD

**Issue by LYZName** [1691665955/MZRefresh#4]
这里是不是判断错了，应该判断footer的吧
![5CC5BF6D-7DE5-4B1D-913F-D1C610CF7372](https://github.com/1691665955/MZRefresh/assets/15816062/e19913d8-3cd2-460d-9a31-ac3db5b58986)

**Comment by 1691665955** [comment]
谢谢反馈，今天下午会更新一个版本

**Comment by 1691665955** [comment]
已发布新版本 0.0.9
